### ISSUE TITLE
[Bug] Problem when installing

### ISSUE THREAD

**Issue by AaronskiiVonskiiKekskii** [qmk/qmk_distro_msys#48]
## Describe the Bug

I installed the qmk_msys.exe on C:\Program Files\QMK_MSYS
When running the shortcut i got this error: 
![error](https://user-images.githubusercontent.com/45239450/116387265-ee909180-a81a-11eb-8aab-5b18d9c8191b.PNG)

Installing it directly onto E:\QMK_MSYS worked.

**Comment by zvecr** [comment]
Shortcuts were fixed in dc007756ddca5b3681ba893f2283cb09f70893f6. While not a full fix, it does at least launch now.

MSYS2 doesnt like installing to folders with spaces, and we inherit that limitation till they roll out fixes.
