### ISSUE TITLE
Automatically get latest driver installer/config

### ISSUE THREAD

**Issue by zvecr** [qmk/qmk_distro_msys#8]
For the short term, a copy was added. However to avoid getting stale, this could either be:

1. downloaded at build time
2. cron action which checks latest and makes PR with changes

Option 2 would match the existing pattern for the MSYS dependency.

**Comment by elfmimi** [comment]
I'd also like to have an option to skip driver install.

**Comment by zvecr** [comment]
> I'd also like to have an option to skip driver install.

Out of scope for this issue, but implemented in ee36ec606b77ec804eb8c4eddeb5a1b336510450.
