### ISSUE TITLE
Windows11不能安装 Windows 11 cannot be installed

### ISSUE THREAD

**Issue by jeromeli002** [qmk/qmk_distro_msys#81]
### Describe the Bug

Windows 11不能安装
Windows 11 cannot be installed

**Comment by zvecr** [comment]
You havent really provided enough context, but within "10.0.22000.51" on a a VM the install of the 2b41f7c beta was fine.

However I had to also install `Microsoft Visual C++ 2013 Redistributable` for the `qmk` command to run.

As its still a preview, this behaviour *might* change so would generally tackle these sorts of issues closer to GA.
