### ISSUE TITLE
[Feature Request] Change installation location

### ISSUE THREAD

**Issue by SafeguardSanakan** [qmk/qmk_distro_msys#94]
### Description

During installation, it is impossible to designate where to install QMK MSYS. Is it possible to add this feature? I would prefer to install this program on a drive that is not my C: drive.

**Comment by zvecr** [comment]
Already implemented,

![](https://raw.githubusercontent.com/qmk/qmk_distro_msys/main/docs/.vuepress/public/install.png)

The installer remembers the previous location, so you will have to uninstall first to get the location prompt again.

**Comment by SafeguardSanakan** [comment]
> 
> 
> Already implemented,
> 
> ![](https://raw.githubusercontent.com/qmk/qmk_distro_msys/main/docs/.vuepress/public/install.png)
> 
> The installer remembers the previous location, so you will have to uninstall first to get the location prompt again.

Incorrect. That's 1.1.0, try 1.5.2. There is no installation dialogue.

![image](https://user-images.githubusercontent.com/38713740/142079138-63846871-b065-4358-816b-0f98710829a9.png)
![image](https://user-images.githubusercontent.com/38713740/142079155-0c9633cb-3674-44c1-b7d7-bc24d10837b1.png)
![image](https://user-images.githubusercontent.com/38713740/142079179-52c3bc1d-9210-473c-86ce-ab5373ecb91e.png)

**Comment by zvecr** [comment]
> Incorrect. That's 1.1.0, try 1.5.2. There is no installation dialogue.

r/confidentlyincorrect?

Win10
![image](https://user-images.githubusercontent.com/16520359/142304662-1464adee-a5d8-4a55-a9e5-4bad519de209.png)

Win11
![install2](https://user-images.githubusercontent.com/16520359/142332048-6c960a01-4307-4442-93c4-7f079d935e4a.png)

**Comment by noroadsleft** [comment]
zvecr said at [10 Nov 2021 14:44 UTC](https://github.com/qmk/qmk_distro_msys/issues/94#issuecomment-965303026)

> The installer remembers the previous location, so you will have to uninstall first to get the location prompt again.
